apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-test
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    # path: "/Users/nelsonm/Desktop/my-pv-data"
    path: "/home/michael/volumes"
    